// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	"github.com/rockset/rockset-go-client/openapi"
	"github.com/rockset/rockset-go-client/option"
	"github.com/rockset/rockset-grafana-backend/pkg/plugin"
)

type FakeRockClient struct {
	GetOrganizationStub        func(context.Context) (openapi.Organization, error)
	getOrganizationMutex       sync.RWMutex
	getOrganizationArgsForCall []struct {
		arg1 context.Context
	}
	getOrganizationReturns struct {
		result1 openapi.Organization
		result2 error
	}
	getOrganizationReturnsOnCall map[int]struct {
		result1 openapi.Organization
		result2 error
	}
	QueryStub        func(context.Context, string, ...option.QueryOption) (openapi.QueryResponse, error)
	queryMutex       sync.RWMutex
	queryArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []option.QueryOption
	}
	queryReturns struct {
		result1 openapi.QueryResponse
		result2 error
	}
	queryReturnsOnCall map[int]struct {
		result1 openapi.QueryResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRockClient) GetOrganization(arg1 context.Context) (openapi.Organization, error) {
	fake.getOrganizationMutex.Lock()
	ret, specificReturn := fake.getOrganizationReturnsOnCall[len(fake.getOrganizationArgsForCall)]
	fake.getOrganizationArgsForCall = append(fake.getOrganizationArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetOrganizationStub
	fakeReturns := fake.getOrganizationReturns
	fake.recordInvocation("GetOrganization", []interface{}{arg1})
	fake.getOrganizationMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRockClient) GetOrganizationCallCount() int {
	fake.getOrganizationMutex.RLock()
	defer fake.getOrganizationMutex.RUnlock()
	return len(fake.getOrganizationArgsForCall)
}

func (fake *FakeRockClient) GetOrganizationCalls(stub func(context.Context) (openapi.Organization, error)) {
	fake.getOrganizationMutex.Lock()
	defer fake.getOrganizationMutex.Unlock()
	fake.GetOrganizationStub = stub
}

func (fake *FakeRockClient) GetOrganizationArgsForCall(i int) context.Context {
	fake.getOrganizationMutex.RLock()
	defer fake.getOrganizationMutex.RUnlock()
	argsForCall := fake.getOrganizationArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRockClient) GetOrganizationReturns(result1 openapi.Organization, result2 error) {
	fake.getOrganizationMutex.Lock()
	defer fake.getOrganizationMutex.Unlock()
	fake.GetOrganizationStub = nil
	fake.getOrganizationReturns = struct {
		result1 openapi.Organization
		result2 error
	}{result1, result2}
}

func (fake *FakeRockClient) GetOrganizationReturnsOnCall(i int, result1 openapi.Organization, result2 error) {
	fake.getOrganizationMutex.Lock()
	defer fake.getOrganizationMutex.Unlock()
	fake.GetOrganizationStub = nil
	if fake.getOrganizationReturnsOnCall == nil {
		fake.getOrganizationReturnsOnCall = make(map[int]struct {
			result1 openapi.Organization
			result2 error
		})
	}
	fake.getOrganizationReturnsOnCall[i] = struct {
		result1 openapi.Organization
		result2 error
	}{result1, result2}
}

func (fake *FakeRockClient) Query(arg1 context.Context, arg2 string, arg3 ...option.QueryOption) (openapi.QueryResponse, error) {
	fake.queryMutex.Lock()
	ret, specificReturn := fake.queryReturnsOnCall[len(fake.queryArgsForCall)]
	fake.queryArgsForCall = append(fake.queryArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []option.QueryOption
	}{arg1, arg2, arg3})
	stub := fake.QueryStub
	fakeReturns := fake.queryReturns
	fake.recordInvocation("Query", []interface{}{arg1, arg2, arg3})
	fake.queryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRockClient) QueryCallCount() int {
	fake.queryMutex.RLock()
	defer fake.queryMutex.RUnlock()
	return len(fake.queryArgsForCall)
}

func (fake *FakeRockClient) QueryCalls(stub func(context.Context, string, ...option.QueryOption) (openapi.QueryResponse, error)) {
	fake.queryMutex.Lock()
	defer fake.queryMutex.Unlock()
	fake.QueryStub = stub
}

func (fake *FakeRockClient) QueryArgsForCall(i int) (context.Context, string, []option.QueryOption) {
	fake.queryMutex.RLock()
	defer fake.queryMutex.RUnlock()
	argsForCall := fake.queryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRockClient) QueryReturns(result1 openapi.QueryResponse, result2 error) {
	fake.queryMutex.Lock()
	defer fake.queryMutex.Unlock()
	fake.QueryStub = nil
	fake.queryReturns = struct {
		result1 openapi.QueryResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeRockClient) QueryReturnsOnCall(i int, result1 openapi.QueryResponse, result2 error) {
	fake.queryMutex.Lock()
	defer fake.queryMutex.Unlock()
	fake.QueryStub = nil
	if fake.queryReturnsOnCall == nil {
		fake.queryReturnsOnCall = make(map[int]struct {
			result1 openapi.QueryResponse
			result2 error
		})
	}
	fake.queryReturnsOnCall[i] = struct {
		result1 openapi.QueryResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeRockClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getOrganizationMutex.RLock()
	defer fake.getOrganizationMutex.RUnlock()
	fake.queryMutex.RLock()
	defer fake.queryMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRockClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ plugin.RockClient = new(FakeRockClient)
